library(lpSolveAPI)
setwd("~/Desktop/Quant Management")
lprec<-read.lp("weigelt part1,2,3.lp")
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)
get.sensitivity.rhs(lprec)
get.dual.solution(lprec)
get.sensitivity.rhs(lprec)
cbind(get.sensitivity.rhs(lprec)$duals[1:11], get.sensitivity.rhs(lprec)$dualsfrom[1:11], get.sensitivity.rhs(lprec)$dualstill[1:11])
cbind(get.sensitivity.rhs(lprec)$duals[12:20], get.sensitivity.rhs(lprec)$dualsfrom[12:20], get.sensitivity.rhs(lprec)$dualstill[12:20])
